name: CI/CD

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (dev / prod)"
        default: "prod"

jobs:
  build:
    name: Build Astro and deploy to S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup NodeJS environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install PNPM dependencies
        working-directory: ./frontend
        run: pnpm install
      - name: Start TinaCMS
        working-directory: ./frontend
        run: pnpm run tina &
      - name: Sleep for 10 seconds so TinaCMS can start
        uses: jakejarvis/wait-action@master
        with:
          time: "10s"
      - name: Compile
        working-directory: ./frontend
        run: pnpm run build
      - name: Remove Tina Admin folder
        working-directory: ./frontend/dist
        run: rm -rf admin
      - name: Deploy to S3 testbucket
        if: github.event.inputs.env == 'dev'
        uses: reggionick/s3-deploy@v4
        with:
          folder: ./frontend/dist
          bucket: remcokerstennl-test
          bucket-region: eu-central-1
          delete-removed: true
          no-cache: true
      - name: Deploy to S3 productionbucket
        if: github.event.inputs.env == 'prod'
        uses: reggionick/s3-deploy@v4
        with:
          folder: ./frontend/dist
          bucket: remcokerstennl
          bucket-region: eu-central-1
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true
